export const schadenfallData: any[] = [
  {
    fall: '334 ZZB: Hagelschaden Auto Feb 2025',
    antragsteller: 'Francesco Di Mascerazzi',
    policennummer: 'TNB - 3035 - 110B',
    schadenfallnummer: '334 ZZB',
    ort: 'Lingen',
    typ: 'Wetterschaden',
    summe: '800 Û',
    datum: '2025-02-28',
    beteiligtePersonen: 'Frederick Zubauer',
    score: '81',
    status: 'In Bearbeitung',
    beurteilung: 'Offen',
    logischeInkonsistenzen: '81',
    zeitlicheInkonsistenzen: '21',
    ungewöhnlicheAngaben: '0%',
    korrelationMitBetrugsfällen: '0',
    schadenshergang:
      'Ich hatte mein Auto draußen geparkt als es über Nacht gehagelt hatte. Die Hagelkörner haben die Windschutzscheibe und die Motorhaube stark beschädigt.',
    einschätzung:
      'Es wurden mehrere schwerwiegende Unstimmigkeiten zwischen der Benutzerbeschreibung und dem erkannten Schadensbild festgestellt. Die Art des Schadens, die Tageszeit des Vorfalls und der Umfang der Schäden stimmen nicht überein. Diese Diskrepanzen deuten auf eine mögliche betrügerische Aktivität hin und erfordern eine gründlichere Untersuchung.',
    auffalligkeiten:
      'Die Benutzerbeschreibung erwähnt einen Hagelschaden, während das erkannte Schadensbild auf einen einzelnen starken Aufprall hindeutet.',
    image: 'image_1.jpg',
  },
  {
    fall: '112 ZZB: Fahrzeug mit Hagelschaden Feb 2025',
    antragsteller: 'Anna Müller',
    policennummer: 'TNB - 3099 - 682A',
    schadenfallnummer: '112 ZZB',
    ort: 'Hamburg',
    typ: 'Wetterschaden',
    summe: '850 Û',
    datum: '2025-02-28',
    beteiligtePersonen: 'Frederick Zubauer',
    score: '5',
    status: 'Abgeschlossen',
    beurteilung: 'Unverdächtig',
    logischeInkonsistenzen: '5',
    zeitlicheInkonsistenzen: '0',
    ungewöhnlicheAngaben: '0',
    korrelationMitBetrugsfällen: '0',
    schadenshergang:
      'Die Motorhaube meines Fahrzeugs wurde durch sehr starken Hagel zerbeult. Die Windschutzscheibe ist gebrochen.',
    einschätzung:
      'Die im Bild sichtbaren Schäden stimmen mit der Beschreibung überein und sind typisch für Hagelschäden. Der Bericht wirkt konsistent.',
    auffalligkeiten:
      'Die Heckpartie des Fahrzeugs wird im Schadenshergang nicht erwähnt.',
    image: 'image_2.jpg',
  },
  {
    fall: '362 ZZB: Abend-Auffahrunfall April 2025',
    antragsteller: 'Melanie Krause',
    policennummer: 'TNB - 3110 - 891F',
    schadenfallnummer: '362 ZZB',
    ort: 'Kassel',
    typ: 'Verkehrsunfall',
    summe: '9,600 Û',
    datum: '2025-02-28',
    beteiligtePersonen: 'Frederick Zubauer',
    score: '96',
    status: 'Abgelehnt',
    beurteilung: 'Betrug',
    logischeInkonsistenzen: '92',
    zeitlicheInkonsistenzen: '32',
    ungewöhnlicheAngaben: '26',
    korrelationMitBetrugsfällen: '0',
    schadenshergang:
      'Ich bin abends auf dem Heimweg gewesen, als das Auto vor mir plötzlich ohne ersichtlichen Grund stark abbremste. Trotz sofortiger Reaktion konnte ich den Aufprall nicht verhindern.',
    einschätzung:
      'Es wurden mehrere schwerwiegende Unstimmigkeiten in der Schilderung des Unfalls identifiziert. Möglicher provozierter Schaden zur Abrechnung.',
    auffalligkeiten:
      'Schadensbild passt nicht zur angegebenen Uhrzeit (18:30 Uhr).',
    image: 'image_3.jpg',
  },
  {
    fall: '419 VMP: Vandalismusschaden nach Demo',
    antragsteller: 'Julian Behrendt',
    policennummer: 'PZK - 6672 - 218M',
    schadenfallnummer: '419 VMP',
    ort: 'Düsseldorf',
    typ: 'Vandalismus',
    summe: '25,000 Û',
    datum: '2025-02-28',
    beteiligtePersonen: 'Frederick Zubauer',
    score: '4',
    status: 'Abgeschlossen',
    beurteilung: 'Unverdächtig',
    logischeInkonsistenzen: '4',
    zeitlicheInkonsistenzen: '0',
    ungewöhnlicheAngaben: '0',
    korrelationMitBetrugsfällen: '0',
    schadenshergang:
      'Mein Fahrzeug war über Nacht am Straßenrand abgestellt. Am Vorabend fand in der Innenstadt eine Demonstration statt. Am nächsten Morgen entdeckte ich massive Lackschäden durch Graffiti, eingeschlagene Fenster sowie Dellen an mehreren Stellen. Es besteht der Verdacht, dass der Schaden im Zusammenhang mit der Demonstration steht.',
    einschätzung:
      'Schadenbild konsistent mit mutwilliger Zerstörung bei Großereignissen. Zusammenhang mit Demonstration nachvollziehbar, aber nicht beweisbar. Polizeiakte liegt bei. Plausibler Vandalismusfall.',
    auffalligkeiten: 'Keine Hinweise auf Manipulation.',
    image: 'image_5.jpg',
  },
  {
    fall: '360 ZZB: Fahrraddiebstahl',
    antragsteller: 'Lisa Brenner',
    policennummer: 'TNB - 3099 - 932B',
    schadenfallnummer: '360 ZZB',
    ort: 'München',
    typ: 'Diebstahl',
    summe: '1,200 Û',
    datum: '2025-02-28',
    beteiligtePersonen: 'Frederick Zubauer',
    score: '12',
    status: 'Abgeschlossen',
    beurteilung: 'Unverdächtig',
    logischeInkonsistenzen: '3',
    zeitlicheInkonsistenzen: '12',
    ungewöhnlicheAngaben: '0',
    korrelationMitBetrugsfällen: '0',
    schadenshergang:
      'Ich hatte mein E-Bike mit einem stabilen Schloss vor dem EDEKA gesichert. Als ich nach 15 Minuten wiederkam, war nur noch das Vorderrad da – samt Schloss. Der Rest des Fahrrads war spurlos verschwunden.',
    einschätzung:
      'Typischer Diebstahlmodus, plausibel. Ungewöhnlich schnelles Vorgehen der Täter. Möglicherweise gezielter Diebstahl durch Profis.',
    auffalligkeiten: 'Teures Rad (E-Bike), aber keine Rahmensicherung.',
    image: 'image_6.jpg',
  },
  {
    fall: '784 DGR: Diebstahl Hotelzimmer',
    antragsteller: 'Sabrina Meier',
    policennummer: 'HTR - 7711 - 204C',
    schadenfallnummer: '784 DGR',
    ort: 'München',
    typ: 'Diebstahl',
    summe: '18,500 Û',
    datum: '2025-02-28',
    beteiligtePersonen: 'Frederick Zubauer',
    score: '95',
    status: 'Abgelehnt',
    beurteilung: 'Betrug',
    logischeInkonsistenzen: '39',
    zeitlicheInkonsistenzen: '48',
    ungewöhnlicheAngaben: '12',
    korrelationMitBetrugsfällen: '88',
    schadenshergang:
      'Ich habe in einem Münchener 4-Sterne-Hotel übernachtet. Als ich nach Hause kam, bemerkte ich, dass mein Diamantring nicht mehr in meiner Reisetasche war. Ich bin mir sicher, dass ich ihn dort verstaut hatte.',
    einschätzung:
      'Ungewöhnlich hoher Wert, keine dokumentierte Sicherung im Safe. Möglicher fingierter Verlust zur Versicherungsabrechnung.',
    auffalligkeiten:
      'Sehr späte Schadensmeldung, kein offizieller Polizeibericht',
    image: 'image_7.jpg',
  },
];

// summe range
export const betragsspanne = [
  'Unter 100 EUR',
  '100 - 1.000 EUR',
  '1.000 - 10.000 EUR',
  '10.000 - 100.000 EUR',
  'Über 100.000 EUR',
];

// score range
export const scoringbereich = [
  'Unter 20',
  '20 - 40',
  '40 - 60',
  '60 - 80',
  '80 - 90',
  'Über 90',
];
