export const descriptionExample = `Hello dear purchasing department,

We need three new workstations with the following equipment by 01.02.2025:
- Desks, one of which is height-adjustable
- Trendoffice chairs and lockable roller cabinets
- Three laptops, one with GPU, each with a 3-year warranty
- Two monitors (from 17 inches, up to 100 euros) per person
- 2 Visual Studio Pro licenses (item no. 23412-M-2343) starting from 01.02. or 01.03.
- 1 large shelf (3x2 meters), please including assembly service

Many thanks in advance!`;

export const tableRows: any[] = [
  {
    name: 'Desk',
    date: '01.02.2025',
    amount: '2',
    vendor: 'IKEA',
    warranty: '2 years',
    size: '',
    price: '599',
    material: 'OE10_D1',
    properties: '',
    description: descriptionExample,
    checked: false,
    suppliers: [
      { name: 'IKEA Deutschland', description: 'https://www.ikea.com/de/de/' },
      { name: 'Home24', description: 'https://www.home24.de/' },
    ],
  },
  {
    name: 'Desk',
    date: '01.02.2025',
    amount: '2',
    vendor: 'IKEA',
    warranty: '2 years',
    size: '',
    price: '799',
    material: 'OE10_D2',
    properties: 'height-adjustable',
    description: descriptionExample,
    checked: false,
    suppliers: [
      { name: 'IKEA Deutschland', description: 'https://www.ikea.com/de/de/' },
      { name: 'OTTO', description: 'https://www.otto.de/' },
    ],
  },
  {
    name: 'Chair',
    date: '01.02.2025',
    amount: '3',
    vendor: 'Trendoffice',
    warranty: '',
    size: '',
    price: '399',
    material: 'OE10_C3',
    properties: '',
    description: descriptionExample,
    checked: false,
    suppliers: [
      { name: 'Staples', description: 'https://www.staples.de/' },
      {
        name: 'Office Discount',
        description: 'https://www.office-discount.de/',
      },
    ],
  },
  {
    name: 'Roller Cabinet',
    date: '01.02.2025',
    amount: '3',
    vendor: 'Trendoffice',
    warranty: '',
    size: '',
    price: '899',
    material: 'OE10_CB4',
    properties: 'lockable',
    description: descriptionExample,
    checked: false,
    suppliers: [
      { name: 'Staples', description: 'https://www.staples.de/' },
      { name: 'Schäfer Shop', description: 'https://www.schaefer-shop.de/' },
    ],
  },
  {
    name: 'Laptop',
    date: '01.02.2025',
    amount: '2',
    vendor: 'Dell',
    warranty: '3 years',
    size: '',
    price: '1450',
    material: 'HW10_L1',
    properties: '',
    description: descriptionExample,
    checked: false,
    suppliers: [
      { name: 'Computacenter', description: 'https://www.computacenter.com/' },
      { name: 'Bechtle', description: 'https://www.bechtle.com/' },
    ],
  },
  {
    name: 'Laptop',
    date: '01.02.2025',
    amount: '1',
    vendor: 'Dell',
    warranty: '3 years',
    size: '',
    price: '1850',
    material: 'HW10_L1',
    properties: 'with GPU',
    description: descriptionExample,
    checked: false,
    suppliers: [
      { name: 'Computacenter', description: 'https://www.computacenter.com/' },
      { name: 'Bechtle', description: 'https://www.bechtle.com/' },
    ],
  },
  {
    name: 'Monitor',
    date: '01.02.2025',
    amount: '6',
    vendor: 'Dell',
    warranty: '4 years',
    size: 'more than 17 inch',
    price: '100',
    material: '',
    properties: '',
    description: descriptionExample,
    checked: false,
    suppliers: [
      { name: 'MediaMarkt', description: 'https://www.mediamarkt.de/' },
      { name: 'Saturn', description: 'https://www.saturn.de/' },
    ],
  },
  {
    name: 'Visual Studio License',
    date: '01.02.2025',
    amount: '1',
    vendor: 'Microsoft',
    warranty: '',
    size: '',
    price: '199',
    material: '23412-M-2343',
    properties: '',
    description: descriptionExample,
    checked: false,
    suppliers: [
      { name: 'SoftwareONE', description: 'https://www.softwareone.com/' },
      { name: 'Compuwave', description: 'https://www.compuwave.de/' },
    ],
  },
  {
    name: 'Visual Studio Pro License',
    date: '01.02.2025',
    amount: '1',
    vendor: 'Microsoft',
    warranty: '',
    size: '',
    price: '299',
    material: '23412-M-2343',
    properties: '',
    description: descriptionExample,
    checked: false,
    suppliers: [
      { name: 'SoftwareONE', description: 'https://www.softwareone.com/' },
      { name: 'Compuwave', description: 'https://www.compuwave.de/' },
    ],
  },
  {
    name: 'Shelf - large',
    date: '01.02.2025',
    amount: '1',
    vendor: '',
    warranty: '',
    size: '3x2 Meter',
    price: '',
    material: '',
    properties: 'Including assembly service',
    description: descriptionExample,
    checked: false,
    rowSpan: 2,
    suppliers: [
      { name: 'Hornbach', description: 'https://www.hornbach.de/' },
      { name: 'OBI', description: 'https://www.obi.de/' },
    ],
  },
  {
    name: 'Assembly Service',
    date: '01.02.2025',
    amount: '1',
    vendor: '',
    warranty: '',
    size: '',
    price: '',
    material: '',
    properties: '',
    isRowSpanChild: true,
    suppliers: [
      { name: 'MyHammer', description: 'https://www.my-hammer.de/' },
      { name: 'TaskRabbit', description: 'https://www.taskrabbit.de/' },
    ],
  },
];

export const chartData: any[] = [
  { name: 'Desk', count: 50, percent: 20 },
  { name: 'Desk', count: 70, percent: 30 },
  { name: 'Chair', count: 120, percent: 30 },
  { name: 'Roller cabinet', count: 150, percent: 30 },
  { name: 'Laptop', count: 200, percent: 40 },
  { name: 'Laptop', count: 250, percent: 50 },
  { name: 'Visual Studio Licence', count: 200, percent: 10 },
  { name: 'Visual Studio Pro Licence', count: 260, percent: 20 },
  { name: 'Networking Equipment', count: 270, percent: 30 },
  { name: 'Assembly Service', count: 100, percent: 20 },
  { name: 'Office Software Subscription', count: 150, percent: 30 },
  { name: 'Keyboard', count: 120, percent: 30 },
  { name: 'Monitor', count: 100, percent: 20 },
];

export const warranties = [
  'Under 1 year',
  '1 year',
  '2 years',
  '3 years',
  '4 years',
  'Over 4 years',
];

export const prices = [
  'Under 50 EUR',
  '50 - 100 EUR',
  '100 - 500 EUR',
  '500 - 750 EUR',
  '750 - 1000 EUR',
  'Over 1000 EUR',
];
